//@Author Alex Issa
package affamato;

import java.util.Map;

import org.json.JSONException;
import org.json.JSONObject;

import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Id;
import com.googlecode.objectify.annotation.Index;

@Entity
public class Ingredient implements Comparable<Ingredient> 
{
    @Id Long id; //The @Id field can be of type Long, long, or String. 
    //If you use Long and save an entity with a null id, a numeric value will be 
    //generated for you using the standard GAE allocator for this kind. If you use 
    //String or the primitive long type, values will never be autogenerated.
    @Index String jsonString;
    @Index Long spoonId;
    @Index String ingredient;
    @Index Float amount;
    @Index String unit;
    @Index String unitShort;
    @Index Map<String,Tuple> nutrition;
    
    //private Ingredient() {}
    public Ingredient(String json) 
    {
    	jsonString = json;
    	
    }

    @Override
    public int compareTo(Ingredient other) 
    {
        return 0;
    }
    
    public static class Tuple{
    	
    }
} 
